{
 "title": "CO2 Monitor detail",
 "time": { "from": "now/d+8h", "to": "now/d-1d+16h" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "monitor_id",
    "label": "CO2Monitor",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: \"co2monitors\",\r\n    tag: \"aranet_id\",\r\n    predicate: (r) => true\r\n)\r\n  |> map(fn: (r) => ({ r with \r\n    label: \r\n      if r._value == \"1\" then \"Room x\" \r\n      else r._value }))"
   }
  ]
 },
 "panels": [
  {
   "title": "Room to sensor id",
   "type": "text",
   "gridPos": { "h": 18, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "| room   | sensor |\n| --------- | ------ |\n|Room x    |  x|\n"
   }
  },
  {
   "title": "CO2",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"aranet_id\"] == \"${monitor_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\r\n  |> last()\r\n  |> drop(columns: [\"_field\"])\r\n",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Median CO2",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"aranet_id\"] == \"${monitor_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\r\n  |> median()\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\"])\r\n  |> map(fn: (r) => ({ r with _time: v.timeRangeStop}))\r\n",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"aranet_id\"] == \"${monitor_id}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_field\"])\r\n",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"aranet_id\"] == \"${monitor_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\r\n  |> drop(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max CO2",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"aranet_id\"] == \"${monitor_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\r\n  |> max()\r\n",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidty",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"aranet_id\"] == \"${monitor_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> drop(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"aranet_id\"] == \"${monitor_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\r\n  |> drop(columns: [\"_field\", \"dev_id\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"aranet_id\"] == \"${monitor_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> movingAverage(n: 10)\r\n  |> drop(columns: [\"_field\", \"dev_id\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"aranet_id\"] == \"${monitor_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> movingAverage(n: 10)\r\n  |> drop(columns: [\"_field\", \"dev_id\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"aranet_id\"] == \"${monitor_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\r\n  |> drop(columns: [\"_field\", \"dev_id\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}