{
 "title": "CO2 Monitors",
 "time": { "from": "now/d+8h", "to": "now/d-1d+16h" },
 "refresh": "5m",
 "panels": [
  {
   "title": "CO2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "  from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\r\n  |> last()\r\n  |> drop(columns: [\"_field\", \"dev_id\"])\r\n  |> map(fn: (r) => ({ r with \r\n    aranet_id: \r\n      if r.aranet_id == \"10\" then \"Room x\" \r\n      else r.aranet_id }))",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> drop(columns: [\"_field\", \"dev_id\"])\r\n  |> map(fn: (r) => ({ r with \r\n    aranet_id: \r\n      if r.aranet_id == \"10\" then \"Room x\" \r\n      else r.aranet_id }))",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max CO2",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\r\n  |> max()\r\n  |> drop(columns: [\"_field\", \"dev_id\"])\r\n  |> map(fn: (r) => ({ r with \r\n    aranet_id: \r\n      if r.aranet_id == \"10\" then \"Room x\" \r\n      else r.aranet_id }))",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Median CO2",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\r\n  |> median()\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\", \"dev_id\"])\r\n//  |> rename(columns: {\"_value\":\"co2\"})\r\n  |> map(fn: (r) => ({ r with _time: v.timeRangeStop}))\r\n  |> map(fn: (r) => ({ r with \r\n    aranet_id: \r\n      if r.aranet_id == \"10\" then \"Room x\" \r\n      else r.aranet_id }))\r\n",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> movingAverage(n: 10)\r\n  |> drop(columns: [\"_field\", \"dev_id\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with \r\n    aranet_id: \r\n      if r.aranet_id == \"10\" then \"Room x\" \r\n      else r.aranet_id }))",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidty",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> movingAverage(n: 10)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_field\", \"dev_id\"])\r\n  |> map(fn: (r) => ({ r with \r\n    aranet_id: \r\n      if r.aranet_id == \"10\" then \"Room x\" \r\n      else r.aranet_id }))",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_field\", \"dev_id\"])\r\n  |> map(fn: (r) => ({ r with \r\n    aranet_id: \r\n      if r.aranet_id == \"10\" then \"Room x\" \r\n      else r.aranet_id }))",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> drop(columns: [\"_field\", \"dev_id\"])\r\n  |> map(fn: (r) => ({ r with \r\n    aranet_id: \r\n      if r.aranet_id == \"10\" then \"Room x\" \r\n      else r.aranet_id }))",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> movingAverage(n: 10)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_field\", \"dev_id\"])\r\n  |> map(fn: (r) => ({ r with \r\n    aranet_id: \r\n      if r.aranet_id == \"10\" then \"Room x\" \r\n      else r.aranet_id }))",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> movingAverage(n: 10)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_field\", \"dev_id\"])\r\n  |> map(fn: (r) => ({ r with \r\n    aranet_id: \r\n      if r.aranet_id == \"10\" then \"Room x\" \r\n      else r.aranet_id }))",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "alias": "$tag_dev_id",
     "groupBy": [
      { "params": [ "dev_id" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"co2monitors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_field\", \"dev_id\"])\r\n  |> map(fn: (r) => ({ r with \r\n    aranet_id: \r\n      if r.aranet_id == \"10\" then \"Room x\" \r\n      else r.aranet_id }))",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}